### ISSUE TITLE
Question about the license for code and models

### ISSUE THREAD

**Issue by jjhaggar** [yihao-meng/AniDoc#13]
Hi! ^_^/

Thank you for sharing this project! It looks like a great resource for both amateur and professional animators! :D

I was wondering if you could clarify the license for the code and models in AniDoc. Knowing the terms of use would help those of us interested in exploring or building upon your work.

If possible, an open license like MIT or Apache 2.0 could make collaboration and contributions easier, but of course, I completely respect whatever you decide :)

**Comment by yihao-meng** [comment]
Thank you for your reminder! I have added a Apache 2.0 license.
