### ISSUE TITLE
long video colorziation

### ISSUE THREAD

**Issue by zyhrainbow** [yihao-meng/AniDoc#3]
Great work! Is it possible to colorize long videos? How to achieve it?

**Comment by yihao-meng** [comment]
Thank you for your recognition! Currently, our model has not been specifically optimized for long videos. Considering that the stable video diffusion (SVD) model we use as the base model has limited generative capabilities, we did not use long sequences  during training. As a result, the performance on long video colorization may degrade. However, we are actively working on a version 2 that focuses on long-term video colorization. Stay tuned!

**Comment by svjack** [comment]
> Thank you for your recognition! Currently, our model has not been specifically optimized for long videos. Considering that the stable video diffusion model we use as the base model has limited generative capabilities, we did not use a large number of frames during training. As a result, the performance on long video colorization may degrade.
> 
> In animation production, videos are typically divided into individual storyboards or shots. Similarly, our current version is designed to colorize videos of a single storyboard or shot length at a time. For long video colorization, we recommend segmenting the video into individual shots (or storyboards), colorizing them separately, and then stitching the results together.
> 
> Additionally, we are actively working on a version 2 that focuses on long-term video colorization to provide better support for these scenarios. Stay tuned!

I have find the inference code limit the frame number to 14 , And hardcode 14 into the code. 
Can you make this feature adaptable to different frame counts? For now, we don't need to consider the effect, just from a functional perspective.
Thank you 🙂

**Comment by yihao-meng** [comment]
> > Thank you for your recognition! Currently, our model has not been specifically optimized for long videos. Considering that the stable video diffusion model we use  as the base model has limited generative capabilities, we did not use a large number of frames during training. As a result, the performance on long video colorization may degrade.
> > In animation production, videos are typically divided into individual storyboards or shots. Similarly, our current version is designed to colorize videos of a single storyboard or shot length at a time. For long video colorization, we recommend segmenting the video into individual shots (or storyboards), colorizing them separately, and then stitching the results together.
> > Additionally, we are actively working on a version 2 that focuses on long-term video colorization to provide better support for these scenarios. Stay tuned!
> 
> I have find the inference code limit the frame number to 14 , And hardcode 14 into the code. Can you make this feature adaptable to different frame counts? For now, we don't need to consider the effect, just from a functional perspective. Thank you 🙂

No problem, I will update this soon.
