### ISSUE TITLE
how create control_image  mp4 file

### ISSUE THREAD

**Issue by libhot** [yihao-meng/AniDoc#5]
when use normal mp4 file as control_image  , raise error:
controlnet_condition= torch.cat([controlnet_sketch_condition, point_map_with_ref], dim=2)   
RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 2 but got size 14 for tensor number 1 in the list.

**Comment by yihao-meng** [comment]
Currently our model expect 14 frames video as input. Therefore, you should preprocess the video into 14 frames, then the bug will be fixed. I will indicate this in the README.

**Comment by libhot** [comment]
It  works!
Thanks
