### ISSUE TITLE
Collaboration Request: AniDoc for Commercial Use

### ISSUE THREAD

**Issue by radna0** [yihao-meng/AniDoc#6]
Hi AniDoc Team,

First off, amazing work on AniDoc! The ability to colorize sketch sequences so accurately is seriously impressive and a game-changer for animators.

I’m the founder of Isekai Creation—an AI project focused on Animation, Anime, and Cartoons. We’re all about making creative tools more accessible and empowering artists. I’d love to collaborate and make AniDoc available as a service for creators and studios. Also, we can provide some compute resources to train even better models! It's not much yet, but I do think it would help researchers like AniDoc to work on amazing causes!

Would you be open to discussing how we can work together, maybe sort out licensing or a partnership? Let me know!

Cheers!

**Comment by yihao-meng** [comment]
Thank you for reaching out and for your kind words about AniDoc! We truly appreciate your recognition of our work and are thrilled to hear that you find our project inspiring and useful.

AniDoc is indeed a research project, and while we’re excited about the potential applications, it’s important to note that it hasn’t yet reached the level of robustness required for commercial user.  At this stage, we do not have plans to use AniDoc for commercial purposes, as our primary focus remains on advancing it as a research project. 

Thank you!

**Comment by radna0** [comment]
Thanks for your response and for clarifying the focus on research—I completely respect and understand that priority.

I’m currently exploring ways to make AI more helpful for artists and animators, aiming to streamline the animation process. My vision is to develop a pipeline that can handle everything from sketch generation to keyframes, in-betweens, backgrounds, and colorization, giving animators full control to tweak each step. I believe this approach could be transformative for the animation and anime industries, far beyond simple video generation models.

Just to clarify, we don’t have any commercial plans for this—we’re simply passionate about supporting the industry and helping creators access tools that can improve their workflows. Your project is truly inspiring, not just for me but for the entire animation community.

I’d love to collaborate in any way and would be happy to support your ongoing research—whether that’s through feedback, testing, or contributing compute resources to really push this technology and put it in the hands of creators/animators. If there’s ever an opportunity to explore making AniDoc more accessible or working on future projects together, I’d be thrilled to stay in touch.

Looking forward to seeing how AniDoc continues to evolve!
