### ISSUE TITLE
small issues in anidoc_inference.sh

### ISSUE THREAD

**Issue by THLsword** [yihao-meng/AniDoc#7]
Very amazing work! 
But there were some minor problems in `anidoc_inference.sh` (solved).
`CUDA_VISIBLE_DEVICES=2` But I only have one gpu, and there is no `sample4_2.mp4` in the `data_test` folder.
So I ran into some trouble when executing `bash scripts_infer/anidoc_inference.sh`.

Thanks and very nice work!

**Comment by yihao-meng** [comment]
Thank you for the reminder! I will quickly update the inference script code to make sure it can work for only one gpu condition. For now you can just replace`CUDA_VISIBLE_DEVICES=2` with `CUDA_VISIBLE_DEVICES=0`

**Comment by IcelandicCenterArtificialIntelligence** [comment]
Has this fix been submitted already? It doesn't seem to be the case.

**Comment by jackylee1** [comment]
File "/home/dell/anaconda3/envs/anidoc/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 522, in forward
    return self.processor(
  File "/home/dell/anaconda3/envs/anidoc/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 743, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "/home/dell/anaconda3/envs/anidoc/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 598, in get_attention_scores
    attention_scores = torch.baddbmm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.71 GiB (GPU 0; 11.75 GiB total capacity; 8.11 GiB already allocated; 1.26 GiB free; 8.53 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF



i have 12vram and 128 ram，WHAT CAN I DO
