### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by sdbds** [yihao-meng/AniDoc#9]
![image](https://github.com/user-attachments/assets/24d16422-9ee4-4636-9f34-0759daf916f5)

Thank you for great work.
I made a Windows version and it works well.
Hope to help your.
Additional non-commercial collaboration matters (regarding model training and datasets) hope to establish contact.
Please leave me an email address or use WeChat.

https://github.com/sdbds/AniDoc-for-windows

感谢你们的工作，效果非常不错。
我做了一个Windows安装版本，参考了Huggingface DEMO制作了一个简单的gradio界面。
另外有一些非商业合作事宜(关于模型训练和数据集)希望能够取得联系。
方便留个邮箱给我，或者使用微信。

**Comment by yihao-meng** [comment]
Thank you so much for your help! My email is ymengas@connect.ust.hk

**Comment by yihao-meng** [comment]
Thank you again for your help! Besides, I think it would be very helpful if the displayed control sequence could be presented as a sketch instead of a color video. Otherwise, users might not clearly understand the task we are working on. Thank you!
